language: node_js
env: 
  global: 
  - secure: DbOIKe0FVNznA1tp14m41H76gauLHvK5wWX2q/gVn4qqpiwlzktu8qvt6Jb+C69MUT4q8T1mhiCwzpBsC5jaFU6JKplbpYe/sF7Piv7vaPJ8rXzTSueVlzBNVVeE7P6opDsH9OrtR3rCEdDG+CEi0qzWogXHG6DfuS52t8z5aaI=
  - secure: L7yXP+nmVrTuRyllx0L4H9wRE+GKagCnwfceOxE1iQigRxk6JvvvSMYdad3u/G2EL8dPqYCHyPfOsWbzO+fYIkyXx4RdVsUomMxfAGL/h3HMqf7oJMhHAkw2hvYPUG0F1Bo0fn3x0o7I+zoZNPj+knBNuG55U3rHGU6k9UQLw5Q=
node_js: 
- 0.1
script: grunt test;
