--- 
node_js: 
- 0.1
env: 
  global: 
  - secure: |-
      exIRj0hA/y9HolTboosEpXFt7QmaaVxzqf34Z9EI7uW2HSdcZhInfFz7anw4
      jV+rU+SgqYqc4Bma1xJ+lE0Ch+5mTpipA+p7ce/4J6jcACraoTf7ERNbs8A6
      ka3BuYsTqkMCG7h1tLdWKNgzUguKbxYBXoaFY22w2XKdL2U6oo0=
  - secure: |-
      faD0G75NjqhnGxVk461nUe1ZxuTHr/ypJbHBx4UyQY+Z6B3MBa5GL5Ut2E5E
      2/0sSkGrjNSwCdoT/ssH1ksqbWWXgZaIj2ndfe2HL/QAK/DPhegejSxBgAz8
      Cee4/6aUJ+YTdaKH6epipav0+x8brkK9fnyckLIuK5NNVDt4YCo=
script: grunt test
language: node_js
